authorization_url: "https://digital.iservices.rte-france.com/token/oauth/"
api_url: "https://digital.iservices.rte-france.com/open_api/actual_generation/v1/actual_generations_per_unit"
content_type: "application/x-www-form-urlencoded"
authorization: "Basic NzFjMTI0NWItOTJhNi00ZWJmLThhMjgtYTMzNGUzYjk0ZGQxOjkwMTNkOTJmLWJiODgtNDViNi1hMGE4LTYyZmQ3ZWQ0ZTdiNw=="

data_name: "actual_generations_per_unit"
values: "values"
value: "value"
pivot_column: "start_date"